# Generated by Django 4.0 on 2021-12-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_rentalitem_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boat',
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='hp',
            field=models.IntegerField(null=True),
        ),
    ]
