# Generated by Django 3.1.7 on 2021-03-17 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalitem',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='rentalItem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='boats.rentalitem'),
            preserve_default=False,
        ),
    ]
