# Generated by Django 3.1.7 on 2021-04-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0008_auto_20210406_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalitem',
            name='endDay',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='startDay',
        ),
    ]
