# Generated by Django 3.1.7 on 2021-04-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0014_auto_20210417_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Interested',
            field=models.IntegerField(default=0),
        ),
    ]
