# Generated by Django 3.1.7 on 2021-04-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0019_auto_20210419_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
    ]
