# Generated by Django 3.1.7 on 2021-04-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0020_auto_20210419_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
