# Generated by Django 3.1.7 on 2021-04-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0021_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_confirmed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
