# Generated by Django 3.1.7 on 2021-04-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=120)),
                ('tuesday', models.CharField(max_length=120)),
                ('wednesday', models.CharField(max_length=120)),
                ('thursday', models.CharField(max_length=120)),
                ('friday', models.CharField(max_length=120)),
                ('saturday', models.CharField(max_length=120)),
                ('sunday', models.CharField(max_length=120)),
            ],
        ),
    ]
