# Generated by Django 3.1.7 on 2021-04-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210428_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='storehour',
            name='name',
            field=models.CharField(default='General Store', max_length=120),
            preserve_default=False,
        ),
    ]
