# Generated by Django 3.1.7 on 2021-03-17 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDay', models.DateField()),
                ('endDay', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('dayPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekdayPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('rentalitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boats.rentalitem')),
                ('hp', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
            bases=('boats.rentalitem',),
        ),
    ]
