# Generated by Django 3.1.7 on 2021-04-06 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0005_rentalitem_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalitem',
            name='dates',
        ),
    ]
