# Generated by Django 3.1.7 on 2021-04-06 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0007_rentalitem_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalitem',
            old_name='dates',
            new_name='endDay',
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='startDay',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
