# Generated by Django 3.1.7 on 2021-04-06 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0009_auto_20210406_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='endDay',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='startDay',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
