# Generated by Django 3.1.7 on 2021-04-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0010_auto_20210406_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Arts', 'Arts'), ('Food', 'Food')], default='Sports', max_length=10)),
            ],
        ),
    ]
