# Generated by Django 3.1.7 on 2021-04-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0023_auto_20210419_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=-1, max_digits=10),
            preserve_default=None,
        ),
    ]
