# Generated by Django 3.1.7 on 2021-04-19 15:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0002_auto_20210419_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default="+16478857314", max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
